/**
 * The template library — the "bunch of templates" half of the workbench.
 *
 * A template is a starting composition: an artboard size, a set of substrate
 * option overrides (the product itself), and an ordered stack of layer specs.
 * `applyTemplate` in `layerModel.js` turns each spec into a real layer and
 * carries the shopper's already-typed words across by `slotRole`, so browsing
 * templates rearranges the design without destroying the writing.
 *
 * Layer spec fields are exactly the layer model's fields. `x`/`y` are the layer
 * CENTRE in artboard space, so a left-aligned block sitting on a 48px margin
 * has `x = 48 + width / 2` and `align: 'left'`.
 *
 * Substrate keys are the option ids the product studios already use:
 *   poster  — artStyle  cosmic | sunburst | retro | minimal | botanical | sunset
 *             paper     cotton | canvas | luster
 *             frame     oak | black | white | gold | none
 *             mat       none | white | offwhite | black
 *             orientation portrait | landscape
 *   apparel — garment   hoodie | tee | jacket | kicks
 *             color     navy | slate | cream | pine | crimson | amber | lavender
 *             accent    ecru | ink | gold | sky | rose | kelly
 *             placement chest | pocket | back
 *             finish    satin | chain | screen | puff
 *   book    — theme     space | magic | sneaker | dino
 *             edition   hardcover | deluxe | softcover
 *
 * Font family ids match the studios: sans | serif | display | cursive (the book
 * studio only offers sans | serif | cursive, so book templates stay off display).
 * Art ids are the stamps in `drawStamp`.
 */

export { STYLE_PRESETS } from './stylePresets';

/* --------------------------------------------------------------- palette -- */

/** Poster inks, taken from the poster studio's ink swatches plus neutrals. */
const INK = {
  white: '#ffffff',
  bone: '#f8fafc',
  ivory: '#fdf6e3',
  gold: '#fcd34d',
  brass: '#d97706',
  sky: '#bae6fd',
  blush: '#fbcfe8',
  mist: '#cbd5e1',
  slate: '#94a3b8',
  deep: '#0f172a',
  night: '#111827',
  midnight: '#0b1120',
};

/** Apparel thread and garment colours, from the apparel studio's tables. */
const THREAD = {
  ecru: '#e7e5e4',
  bone: '#f8fafc',
  ink: '#111827',
  gold: '#d97706',
  lemon: '#fcd34d',
  sky: '#38bdf8',
  rose: '#f472b6',
  kelly: '#16a34a',
  pine: '#064e3b',
  navy: '#1e293b',
  graphite: '#475569',
  dust: '#94a3b8',
};

/** Book papers and inks — warmer than the poster set, keepsake-leaning. */
const PAGE = {
  cream: '#faf5ea',
  gilt: '#c9a227',
  antique: '#8a6d1f',
  cocoa: '#3f2d16',
  bark: '#5b4a33',
  starlight: '#e2e8f0',
  dusk: '#7c8ba1',
  night: '#0b1120',
  slate: '#1e293b',
  violet: '#7c3aed',
  lilac: '#ddd6fe',
  lavender: '#a78bfa',
  lemon: '#fcd34d',
};

/* --------------------------------------------------------------- shapes -- */

const POSTER_PORTRAIT = { width: 440, height: 586 };
const POSTER_LANDSCAPE = { width: 586, height: 440 };

const CHEST = { width: 360, height: 300 };
const BACK = { width: 400, height: 480 };
const POCKET = { width: 180, height: 180 };
const PATCH = { width: 240, height: 240 };

const COVER = { width: 420, height: 540 };
const SPREAD = { width: 720, height: 460 };

/* -------------------------------------------------------------- builders -- */

/**
 * Small factories so a composition reads as a composition rather than as a wall
 * of repeated `type:` keys. They are plain object literals — no state, no
 * identity, nothing a caller can mutate by accident.
 *
 * Every non-text layer still carries a `slotRole` ('accent' for rules, panels
 * and small marks, 'image' for the focal artwork). Without one, `applyTemplate`
 * treats it as a layer the shopper added themselves and keeps it when they swap
 * template, so decorations from every template they browsed pile up.
 */
const slot = (slotRole, name, props) => ({
  type: 'text',
  slotRole,
  name,
  ...props,
});

const panel = (name, props) => ({
  type: 'shape',
  slotRole: 'accent',
  shape: 'rect',
  name,
  ...props,
});

const rule = (name, props) => ({
  type: 'shape',
  slotRole: 'accent',
  shape: 'rect',
  name,
  radius: 0,
  ...props,
});

const oval = (name, props) => ({
  type: 'shape',
  slotRole: 'accent',
  shape: 'ellipse',
  name,
  ...props,
});

/** The focal artwork of a composition. */
const art = (name, props) => ({
  type: 'art',
  slotRole: 'image',
  name,
  ...props,
});

/** Decorative artwork — confetti, a small seal, a scattered star. */
const mark = (name, props) => ({
  type: 'art',
  slotRole: 'accent',
  name,
  ...props,
});

/* ========================================================= poster ======== */

/* -- Editorial: mastheads, rules and long captions. Reads like a journal. -- */

const POSTER_EDITORIAL = [
  {
    id: 'poster-editorial-stack',
    name: 'Editorial Stack',
    category: 'Editorial',
    description:
      'Left-aligned masthead over a hairline rule, with a long caption dropped to the foot.',
    artboard: POSTER_PORTRAIT,
    substrate: {
      artStyle: 'minimal',
      paper: 'cotton',
      frame: 'oak',
      mat: 'offwhite',
      orientation: 'portrait',
    },
    layers: [
      slot('eyebrow', 'Dateline', {
        text: 'FIELD NOTES / NO. 07',
        x: 220,
        y: 96,
        width: 344,
        height: 18,
        fontFamily: 'sans',
        fontSize: 13,
        fontWeight: 600,
        letterSpacing: 4,
        textTransform: 'uppercase',
        align: 'left',
        color: INK.mist,
      }),
      slot('title', 'Title', {
        text: 'The Bravest Explorer',
        x: 220,
        y: 172,
        width: 344,
        height: 128,
        fontFamily: 'serif',
        fontSize: 56,
        fontWeight: 700,
        lineHeight: 1.04,
        align: 'left',
        color: INK.white,
      }),
      rule('Hairline', {
        x: 220,
        y: 254,
        width: 344,
        height: 2,
        fill: INK.gold,
      }),
      slot('subtitle', 'Subtitle', {
        text: 'A keepsake print for Maya, age six',
        x: 220,
        y: 290,
        width: 344,
        height: 26,
        fontFamily: 'sans',
        fontSize: 19,
        fontWeight: 400,
        align: 'left',
        color: INK.ivory,
      }),
      art('Compass', {
        art: 'compass',
        x: 123,
        y: 402,
        width: 150,
        height: 150,
        tint: INK.gold,
      }),
      slot('caption', 'Caption', {
        text: 'Drawn by hand and printed once, on cotton rag, in the summer she learned to climb the tall oak.',
        x: 220,
        y: 524,
        width: 344,
        height: 60,
        fontFamily: 'sans',
        fontSize: 13,
        fontWeight: 400,
        lineHeight: 1.5,
        align: 'left',
        color: INK.mist,
      }),
    ],
  },
  {
    id: 'poster-editorial-split',
    name: 'Split Masthead',
    category: 'Editorial',
    description:
      'Landscape sheet cut by a full-height rule: title on the left, the story on the right.',
    artboard: POSTER_LANDSCAPE,
    substrate: {
      artStyle: 'cosmic',
      paper: 'cotton',
      frame: 'black',
      mat: 'none',
      orientation: 'landscape',
    },
    layers: [
      rule('Gutter rule', {
        x: 293,
        y: 220,
        width: 2,
        height: 300,
        fill: INK.slate,
        opacity: 0.6,
      }),
      slot('eyebrow', 'Dateline', {
        text: 'ONE OF ONE',
        x: 163,
        y: 104,
        width: 229,
        height: 16,
        fontFamily: 'sans',
        fontSize: 12,
        fontWeight: 600,
        letterSpacing: 4,
        textTransform: 'uppercase',
        align: 'right',
        color: INK.slate,
      }),
      slot('title', 'Title', {
        text: 'The Bravest Explorer',
        x: 163,
        y: 190,
        width: 229,
        height: 124,
        fontFamily: 'serif',
        fontSize: 44,
        fontWeight: 700,
        lineHeight: 1.02,
        align: 'right',
        color: INK.white,
      }),
      slot('badge', 'Year', {
        text: 'SUMMER 2026',
        x: 163,
        y: 292,
        width: 229,
        height: 20,
        fontFamily: 'sans',
        fontSize: 12,
        fontWeight: 700,
        letterSpacing: 3,
        textTransform: 'uppercase',
        align: 'right',
        color: INK.gold,
      }),
      slot('subtitle', 'Subtitle', {
        text: 'For Maya, on her sixth birthday',
        x: 424,
        y: 152,
        width: 229,
        height: 52,
        fontFamily: 'serif',
        fontSize: 19,
        fontWeight: 500,
        lineHeight: 1.35,
        align: 'left',
        color: INK.ivory,
      }),
      slot('body', 'Story', {
        text: 'She packed a torch, two plums and a map she drew herself, then walked to the end of the garden and called it the end of the world.',
        x: 424,
        y: 252,
        width: 229,
        height: 112,
        fontFamily: 'sans',
        fontSize: 13,
        fontWeight: 400,
        lineHeight: 1.6,
        align: 'left',
        color: INK.mist,
      }),
      slot('caption', 'Footer', {
        text: 'PRINTED ON ARCHIVAL COTTON RAG',
        x: 293,
        y: 398,
        width: 490,
        height: 18,
        fontFamily: 'sans',
        fontSize: 11,
        fontWeight: 500,
        letterSpacing: 5,
        textTransform: 'uppercase',
        align: 'center',
        color: INK.slate,
      }),
    ],
  },
  {
    id: 'poster-editorial-index',
    name: 'Index Line',
    category: 'Editorial',
    description:
      'Two full-width rules bracket the sheet, with the title dropped low and numbered.',
    artboard: POSTER_PORTRAIT,
    substrate: {
      artStyle: 'sunset',
      paper: 'luster',
      frame: 'black',
      mat: 'none',
      orientation: 'portrait',
    },
    layers: [
      rule('Top rule', {
        x: 220,
        y: 104,
        width: 344,
        height: 2,
        fill: INK.ivory,
      }),
      slot('eyebrow', 'Section', {
        text: 'EXPLORERS',
        x: 168,
        y: 82,
        width: 240,
        height: 16,
        fontFamily: 'sans',
        fontSize: 12,
        fontWeight: 700,
        letterSpacing: 5,
        textTransform: 'uppercase',
        align: 'left',
        color: INK.ivory,
      }),
      slot('badge', 'Number', {
        text: 'No. 07',
        x: 362,
        y: 82,
        width: 60,
        height: 16,
        fontFamily: 'sans',
        fontSize: 12,
        fontWeight: 700,
        letterSpacing: 1,
        align: 'right',
        color: INK.gold,
      }),
      panel('Accent square', {
        x: 57,
        y: 202,
        width: 18,
        height: 18,
        radius: 0,
        fill: INK.gold,
      }),
      slot('title', 'Title', {
        text: 'Maya The Brave',
        x: 220,
        y: 302,
        width: 344,
        height: 134,
        fontFamily: 'display',
        fontSize: 62,
        fontWeight: 800,
        lineHeight: 0.98,
        letterSpacing: -1,
        textTransform: 'uppercase',
        align: 'left',
        color: INK.white,
      }),
      slot('subtitle', 'Subtitle', {
        text: 'Six years old and entirely unafraid',
        x: 220,
        y: 400,
        width: 344,
        height: 26,
        fontFamily: 'sans',
        fontSize: 18,
        fontWeight: 400,
        align: 'left',
        color: INK.ivory,
      }),
      rule('Bottom rule', {
        x: 220,
        y: 470,
        width: 344,
        height: 2,
        fill: INK.ivory,
      }),
      slot('caption', 'Footer', {
        text: 'MADE FOR HER, ONCE, IN JUNE',
        x: 220,
        y: 498,
        width: 344,
        height: 16,
        fontFamily: 'sans',
        fontSize: 12,
        fontWeight: 500,
        letterSpacing: 3,
        textTransform: 'uppercase',
        align: 'left',
        color: INK.mist,
      }),
    ],
  },
];

/* -- Bold Type: the type is the artwork. Oversized, blocked, knocked out. -- */

const POSTER_BOLD = [
  {
    id: 'poster-type-slab',
    name: 'Giant Slab',
    category: 'Bold Type',
    description:
      'Oversized display type filling the sheet, with the subtitle knocked out of a solid band.',
    artboard: POSTER_PORTRAIT,
    substrate: {
      artStyle: 'sunburst',
      paper: 'luster',
      frame: 'black',
      mat: 'none',
      orientation: 'portrait',
    },
    layers: [
      slot('eyebrow', 'Eyebrow', {
        text: 'NOW ARRIVING',
        x: 220,
        y: 92,
        width: 384,
        height: 18,
        fontFamily: 'sans',
        fontSize: 13,
        fontWeight: 700,
        letterSpacing: 6,
        textTransform: 'uppercase',
        align: 'center',
        color: INK.night,
      }),
      slot('title', 'Title', {
        text: 'The Bravest Explorer',
        x: 220,
        y: 252,
        width: 384,
        height: 264,
        fontFamily: 'display',
        fontSize: 92,
        fontWeight: 900,
        lineHeight: 0.92,
        letterSpacing: -2,
        textTransform: 'uppercase',
        align: 'center',
        color: INK.night,
      }),
      panel('Subtitle band', {
        x: 220,
        y: 420,
        width: 384,
        height: 56,
        radius: 4,
        fill: INK.night,
      }),
      slot('subtitle', 'Subtitle', {
        text: 'MAYA WREN, AGE SIX',
        x: 220,
        y: 420,
        width: 360,
        height: 30,
        fontFamily: 'sans',
        fontSize: 20,
        fontWeight: 700,
        letterSpacing: 6,
        textTransform: 'uppercase',
        align: 'center',
        color: INK.gold,
      }),
      slot('caption', 'Caption', {
        text: 'ONE PRINT, ONE EXPLORER',
        x: 220,
        y: 520,
        width: 384,
        height: 18,
        fontFamily: 'sans',
        fontSize: 12,
        fontWeight: 600,
        letterSpacing: 4,
        textTransform: 'uppercase',
        align: 'center',
        color: INK.night,
      }),
    ],
  },
  {
    id: 'poster-type-corner-block',
    name: 'Corner Block',
    category: 'Bold Type',
    description:
      'A full-bleed colour block across the top half, with the type anchored low and left.',
    artboard: POSTER_PORTRAIT,
    substrate: {
      artStyle: 'cosmic',
      paper: 'cotton',
      frame: 'oak',
      mat: 'none',
      orientation: 'portrait',
    },
    layers: [
      panel('Colour block', {
        x: 220,
        y: 150,
        width: 440,
        height: 300,
        radius: 0,
        fill: INK.midnight,
      }),
      art('Rocket', {
        art: 'rocket',
        x: 220,
        y: 150,
        width: 170,
        height: 170,
        tint: INK.gold,
      }),
      slot('title', 'Title', {
        text: 'Off We Go',
        x: 220,
        y: 396,
        width: 344,
        height: 106,
        fontFamily: 'display',
        fontSize: 52,
        fontWeight: 800,
        lineHeight: 1,
        textTransform: 'uppercase',
        align: 'left',
        color: INK.white,
      }),
      slot('subtitle', 'Subtitle', {
        text: 'Maya Wren, chief of the garden expedition',
        x: 220,
        y: 472,
        width: 344,
        height: 26,
        fontFamily: 'sans',
        fontSize: 18,
        fontWeight: 400,
        align: 'left',
        color: INK.sky,
      }),
      slot('caption', 'Caption', {
        text: 'JUNE 2026 / NO. 1 OF 1',
        x: 220,
        y: 522,
        width: 344,
        height: 16,
        fontFamily: 'sans',
        fontSize: 12,
        fontWeight: 500,
        letterSpacing: 3,
        textTransform: 'uppercase',
        align: 'left',
        color: INK.slate,
      }),
    ],
  },
  {
    id: 'poster-type-stacked-bars',
    name: 'Stacked Bars',
    category: 'Bold Type',
    description:
      'Title and subtitle each ride their own bar, offset against one another.',
    artboard: POSTER_PORTRAIT,
    substrate: {
      artStyle: 'retro',
      paper: 'luster',
      frame: 'black',
      mat: 'none',
      orientation: 'portrait',
    },
    layers: [
      slot('eyebrow', 'Eyebrow', {
        text: 'PRESENTING',
        x: 220,
        y: 96,
        width: 360,
        height: 18,
        fontFamily: 'sans',
        fontSize: 13,
        fontWeight: 700,
        letterSpacing: 6,
        textTransform: 'uppercase',
        align: 'center',
        color: INK.blush,
      }),
      panel('Title bar', {
        x: 200,
        y: 210,
        width: 330,
        height: 132,
        radius: 2,
        fill: INK.night,
      }),
      slot('title', 'Title', {
        text: 'The Bravest Explorer',
        x: 200,
        y: 210,
        width: 306,
        height: 110,
        fontFamily: 'display',
        fontSize: 46,
        fontWeight: 900,
        lineHeight: 1,
        textTransform: 'uppercase',
        align: 'center',
        color: INK.gold,
      }),
      panel('Subtitle bar', {
        x: 252,
        y: 318,
        width: 330,
        height: 54,
        radius: 2,
        fill: INK.gold,
      }),
      slot('subtitle', 'Subtitle', {
        text: 'MAYA WREN',
        x: 252,
        y: 318,
        width: 300,
        height: 30,
        fontFamily: 'sans',
        fontSize: 20,
        fontWeight: 800,
        letterSpacing: 4,
        textTransform: 'uppercase',
        align: 'center',
        color: INK.night,
      }),
      mark('Star', {
        art: 'star',
        x: 220,
        y: 432,
        width: 64,
        height: 64,
        tint: INK.gold,
      }),
      slot('caption', 'Caption', {
        text: 'Six years old this summer',
        x: 220,
        y: 504,
        width: 360,
        height: 20,
        fontFamily: 'sans',
        fontSize: 14,
        fontWeight: 400,
        align: 'center',
        color: INK.ivory,
      }),
    ],
  },
];

/* -- Illustrated: the stamps lead, the type supports. ---------------------- */

const POSTER_ILLUSTRATED = [
  {
    id: 'poster-illustrated-hero',
    name: 'Hero Portrait',
    category: 'Illustrated',
    description:
      'A single mascot centred on a soft halo, with the name set large beneath it.',
    artboard: POSTER_PORTRAIT,
    substrate: {
      artStyle: 'cosmic',
      paper: 'cotton',
      frame: 'oak',
      mat: 'none',
      orientation: 'portrait',
    },
    layers: [
      oval('Halo', {
        x: 220,
        y: 250,
        width: 306,
        height: 306,
        fill: '#172554',
        opacity: 0.75,
      }),
      art('Mascot', {
        art: 'mascot_luna',
        x: 220,
        y: 250,
        width: 250,
        height: 250,
      }),
      slot('eyebrow', 'Eyebrow', {
        text: 'STARLIGHT PATROL',
        x: 220,
        y: 92,
        width: 360,
        height: 18,
        fontFamily: 'sans',
        fontSize: 13,
        fontWeight: 600,
        letterSpacing: 5,
        textTransform: 'uppercase',
        align: 'center',
        color: INK.sky,
      }),
      slot('title', 'Title', {
        text: 'Luna & Maya',
        x: 220,
        y: 422,
        width: 360,
        height: 56,
        fontFamily: 'display',
        fontSize: 46,
        fontWeight: 800,
        align: 'center',
        color: INK.white,
      }),
      slot('subtitle', 'Subtitle', {
        text: 'Keeping watch over the whole back garden',
        x: 220,
        y: 476,
        width: 340,
        height: 26,
        fontFamily: 'sans',
        fontSize: 17,
        fontWeight: 400,
        align: 'center',
        color: INK.ivory,
      }),
      slot('caption', 'Caption', {
        text: 'FOR MAYA, ON HER SIXTH BIRTHDAY',
        x: 220,
        y: 532,
        width: 360,
        height: 16,
        fontFamily: 'sans',
        fontSize: 12,
        fontWeight: 500,
        letterSpacing: 3,
        textTransform: 'uppercase',
        align: 'center',
        color: INK.slate,
      }),
    ],
  },
  {
    id: 'poster-illustrated-scene',
    name: 'Night Scene',
    category: 'Illustrated',
    description:
      'A scattered night sky above a dark horizon band, with the title sitting on the ground.',
    artboard: POSTER_PORTRAIT,
    substrate: {
      artStyle: 'cosmic',
      paper: 'luster',
      frame: 'black',
      mat: 'none',
      orientation: 'portrait',
    },
    layers: [
      panel('Horizon', {
        x: 220,
        y: 560,
        width: 440,
        height: 120,
        radius: 0,
        fill: INK.midnight,
      }),
      mark('Planet', {
        art: 'planet',
        x: 340,
        y: 140,
        width: 110,
        height: 110,
      }),
      mark('Star', { art: 'star', x: 96, y: 112, width: 44, height: 44 }),
      mark('Sparkle', {
        art: 'sparkle',
        x: 150,
        y: 212,
        width: 32,
        height: 32,
      }),
      art('Rocket', { art: 'rocket', x: 220, y: 302, width: 150, height: 150 }),
      slot('title', 'Title', {
        text: 'To The Far Stars',
        x: 220,
        y: 430,
        width: 380,
        height: 54,
        fontFamily: 'display',
        fontSize: 44,
        fontWeight: 800,
        textTransform: 'uppercase',
        align: 'center',
        color: INK.white,
      }),
      slot('subtitle', 'Subtitle', {
        text: 'Maya Wren, navigator, age six',
        x: 220,
        y: 486,
        width: 360,
        height: 24,
        fontFamily: 'sans',
        fontSize: 17,
        fontWeight: 400,
        align: 'center',
        color: INK.sky,
      }),
      slot('caption', 'Caption', {
        text: 'LIGHTS OUT AT EIGHT, LAUNCH AT NINE',
        x: 220,
        y: 536,
        width: 380,
        height: 16,
        fontFamily: 'sans',
        fontSize: 12,
        fontWeight: 500,
        letterSpacing: 3,
        textTransform: 'uppercase',
        align: 'center',
        color: INK.slate,
      }),
    ],
  },
];

/* -- Minimal: almost nothing on the sheet, placed exactly. ----------------- */

const POSTER_MINIMAL = [
  {
    id: 'poster-minimal-corner',
    name: 'Quiet Corner',
    category: 'Minimal',
    description:
      'Small type parked in the lower-right corner, the rest of the sheet left as air.',
    artboard: POSTER_PORTRAIT,
    substrate: {
      artStyle: 'minimal',
      paper: 'cotton',
      frame: 'white',
      mat: 'white',
      orientation: 'portrait',
    },
    layers: [
      slot('eyebrow', 'Eyebrow', {
        text: 'ONE OF ONE',
        x: 126,
        y: 58,
        width: 140,
        height: 16,
        fontFamily: 'sans',
        fontSize: 11,
        fontWeight: 600,
        letterSpacing: 4,
        textTransform: 'uppercase',
        align: 'left',
        color: INK.slate,
      }),
      oval('Dot', {
        x: 384,
        y: 372,
        width: 10,
        height: 10,
        fill: INK.gold,
      }),
      slot('title', 'Title', {
        text: 'The Bravest Explorer',
        x: 244,
        y: 430,
        width: 280,
        height: 80,
        fontFamily: 'serif',
        fontSize: 34,
        fontWeight: 500,
        lineHeight: 1.12,
        align: 'right',
        color: INK.white,
      }),
      slot('subtitle', 'Subtitle', {
        text: 'Maya Wren, age six',
        x: 244,
        y: 492,
        width: 280,
        height: 22,
        fontFamily: 'sans',
        fontSize: 15,
        fontWeight: 400,
        align: 'right',
        color: INK.mist,
      }),
      rule('Hairline', {
        x: 334,
        y: 524,
        width: 100,
        height: 1,
        fill: INK.slate,
      }),
      slot('caption', 'Caption', {
        text: 'JUNE 2026',
        x: 244,
        y: 546,
        width: 280,
        height: 14,
        fontFamily: 'sans',
        fontSize: 11,
        fontWeight: 500,
        letterSpacing: 3,
        textTransform: 'uppercase',
        align: 'right',
        color: INK.slate,
      }),
    ],
  },
  {
    id: 'poster-minimal-hairline-frame',
    name: 'Hairline Frame',
    category: 'Minimal',
    description:
      'A four-sided hairline border with a short centred stack floating inside it.',
    artboard: POSTER_PORTRAIT,
    substrate: {
      artStyle: 'minimal',
      paper: 'cotton',
      frame: 'oak',
      mat: 'offwhite',
      orientation: 'portrait',
    },
    layers: [
      rule('Frame top', {
        x: 220,
        y: 44,
        width: 352,
        height: 1,
        fill: INK.mist,
      }),
      rule('Frame bottom', {
        x: 220,
        y: 542,
        width: 352,
        height: 1,
        fill: INK.mist,
      }),
      rule('Frame left', {
        x: 44,
        y: 293,
        width: 1,
        height: 498,
        fill: INK.mist,
      }),
      rule('Frame right', {
        x: 396,
        y: 293,
        width: 1,
        height: 498,
        fill: INK.mist,
      }),
      slot('eyebrow', 'Eyebrow', {
        text: 'A KEEPSAKE',
        x: 220,
        y: 200,
        width: 300,
        height: 16,
        fontFamily: 'sans',
        fontSize: 12,
        fontWeight: 500,
        letterSpacing: 5,
        textTransform: 'uppercase',
        align: 'center',
        color: INK.slate,
      }),
      slot('title', 'Title', {
        text: 'The Bravest Explorer',
        x: 220,
        y: 272,
        width: 300,
        height: 84,
        fontFamily: 'serif',
        fontSize: 36,
        fontWeight: 500,
        lineHeight: 1.12,
        align: 'center',
        color: INK.white,
      }),
      rule('Short rule', {
        x: 220,
        y: 336,
        width: 48,
        height: 1,
        fill: INK.gold,
      }),
      slot('subtitle', 'Subtitle', {
        text: 'For Maya, on her sixth birthday',
        x: 220,
        y: 372,
        width: 300,
        height: 22,
        fontFamily: 'sans',
        fontSize: 15,
        fontWeight: 400,
        align: 'center',
        color: INK.mist,
      }),
      slot('caption', 'Caption', {
        text: 'PRINTED ONCE, IN JUNE',
        x: 220,
        y: 490,
        width: 300,
        height: 14,
        fontFamily: 'sans',
        fontSize: 11,
        fontWeight: 500,
        letterSpacing: 3,
        textTransform: 'uppercase',
        align: 'center',
        color: INK.slate,
      }),
    ],
  },
];

/* -- Celebration & Vintage: one each, the occasion pieces. ----------------- */

const POSTER_OCCASION = [
  {
    id: 'poster-celebration-arch',
    name: 'Birthday Arch',
    category: 'Celebration',
    description:
      'A rounded arch panel holding the age, with confetti scattered above the name.',
    artboard: POSTER_PORTRAIT,
    substrate: {
      artStyle: 'retro',
      paper: 'luster',
      frame: 'gold',
      mat: 'offwhite',
      orientation: 'portrait',
    },
    layers: [
      panel('Arch', {
        x: 220,
        y: 270,
        width: 300,
        height: 380,
        radius: 150,
        fill: INK.night,
      }),
      oval('Confetti dot', {
        x: 110,
        y: 118,
        width: 16,
        height: 16,
        fill: INK.gold,
      }),
      panel('Confetti chip', {
        x: 330,
        y: 96,
        width: 14,
        height: 14,
        radius: 2,
        rotation: 20,
        fill: INK.blush,
      }),
      oval('Confetti speck', {
        x: 70,
        y: 172,
        width: 10,
        height: 10,
        fill: INK.sky,
      }),
      mark('Crown', {
        art: 'crown',
        x: 220,
        y: 108,
        width: 72,
        height: 72,
        tint: INK.gold,
      }),
      slot('badge', 'Age', {
        text: 'SIX',
        x: 220,
        y: 184,
        width: 220,
        height: 92,
        fontFamily: 'display',
        fontSize: 76,
        fontWeight: 900,
        letterSpacing: 4,
        align: 'center',
        color: INK.gold,
      }),
      slot('title', 'Title', {
        text: 'Maya Wren',
        x: 220,
        y: 292,
        width: 260,
        height: 88,
        fontFamily: 'serif',
        fontSize: 38,
        fontWeight: 700,
        lineHeight: 1.05,
        align: 'center',
        color: INK.white,
      }),
      slot('subtitle', 'Subtitle', {
        text: 'Six years of brave and bright',
        x: 220,
        y: 374,
        width: 260,
        height: 24,
        fontFamily: 'sans',
        fontSize: 16,
        fontWeight: 400,
        align: 'center',
        color: INK.blush,
      }),
      slot('caption', 'Caption', {
        text: 'THE TWELFTH OF JUNE',
        x: 220,
        y: 520,
        width: 320,
        height: 16,
        fontFamily: 'sans',
        fontSize: 12,
        fontWeight: 500,
        letterSpacing: 3,
        textTransform: 'uppercase',
        align: 'center',
        color: INK.mist,
      }),
    ],
  },
  {
    id: 'poster-vintage-seal',
    name: 'Vintage Seal',
    category: 'Vintage',
    description:
      'A struck-metal seal with the title inside the ring and a dated footer beneath.',
    artboard: POSTER_PORTRAIT,
    substrate: {
      artStyle: 'botanical',
      paper: 'canvas',
      frame: 'gold',
      mat: 'black',
      orientation: 'portrait',
    },
    layers: [
      oval('Seal ring', {
        x: 220,
        y: 250,
        width: 300,
        height: 300,
        fill: INK.gold,
      }),
      oval('Seal field', {
        x: 220,
        y: 250,
        width: 276,
        height: 276,
        fill: INK.deep,
      }),
      slot('eyebrow', 'Eyebrow', {
        text: 'CERTIFIED BRAVE',
        x: 220,
        y: 170,
        width: 220,
        height: 16,
        fontFamily: 'sans',
        fontSize: 12,
        fontWeight: 600,
        letterSpacing: 5,
        textTransform: 'uppercase',
        align: 'center',
        color: INK.gold,
      }),
      slot('title', 'Title', {
        text: 'The Bravest Explorer',
        x: 220,
        y: 236,
        width: 230,
        height: 80,
        fontFamily: 'serif',
        fontSize: 34,
        fontWeight: 700,
        lineHeight: 1.05,
        align: 'center',
        color: INK.ivory,
      }),
      rule('Seal rule', {
        x: 220,
        y: 288,
        width: 60,
        height: 2,
        fill: INK.gold,
      }),
      slot('subtitle', 'Subtitle', {
        text: 'MAYA WREN, AGE SIX',
        x: 220,
        y: 320,
        width: 220,
        height: 20,
        fontFamily: 'sans',
        fontSize: 14,
        fontWeight: 500,
        letterSpacing: 2,
        textTransform: 'uppercase',
        align: 'center',
        color: INK.ivory,
      }),
      mark('Star', {
        art: 'star',
        x: 220,
        y: 438,
        width: 44,
        height: 44,
        tint: INK.gold,
      }),
      slot('caption', 'Caption', {
        text: 'ISSUED THE TWELFTH OF JUNE, TWO THOUSAND TWENTY SIX',
        x: 220,
        y: 520,
        width: 344,
        height: 30,
        fontFamily: 'sans',
        fontSize: 11,
        fontWeight: 500,
        lineHeight: 1.5,
        letterSpacing: 3,
        textTransform: 'uppercase',
        align: 'center',
        color: INK.mist,
      }),
    ],
  },
];

/* ======================================================== apparel ======== */

/* -- Varsity: arches, nameplates, big numerals. --------------------------- */

const APPAREL_VARSITY = [
  {
    id: 'apparel-varsity-arch',
    name: 'Varsity Arch',
    category: 'Varsity',
    description:
      'Team-name arch over a crest, closed off by a solid nameplate bar along the bottom.',
    artboard: CHEST,
    substrate: {
      garment: 'hoodie',
      color: 'navy',
      accent: 'gold',
      placement: 'chest',
      finish: 'chain',
    },
    layers: [
      slot('title', 'Team name', {
        text: 'EXPLORERS',
        x: 180,
        y: 74,
        width: 330,
        height: 56,
        fontFamily: 'display',
        fontSize: 46,
        fontWeight: 900,
        letterSpacing: 2,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.ecru,
      }),
      art('Crest', {
        art: 'badge_hero',
        x: 180,
        y: 160,
        width: 110,
        height: 110,
      }),
      slot('badge', 'Number', {
        text: '06',
        x: 300,
        y: 160,
        width: 60,
        height: 50,
        fontFamily: 'display',
        fontSize: 40,
        fontWeight: 900,
        align: 'center',
        color: THREAD.lemon,
      }),
      panel('Nameplate', {
        x: 180,
        y: 244,
        width: 300,
        height: 44,
        radius: 6,
        fill: THREAD.gold,
      }),
      slot('subtitle', 'Name', {
        text: 'MAYA WREN',
        x: 180,
        y: 244,
        width: 280,
        height: 28,
        fontFamily: 'display',
        fontSize: 22,
        fontWeight: 800,
        letterSpacing: 3,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.ink,
      }),
    ],
  },
  {
    id: 'apparel-varsity-numeral',
    name: 'Big Numeral',
    category: 'Varsity',
    description:
      'A back print built around one huge numeral, ruled off above and below.',
    artboard: BACK,
    substrate: {
      garment: 'jacket',
      color: 'crimson',
      accent: 'ecru',
      placement: 'back',
      finish: 'satin',
    },
    layers: [
      slot('title', 'Team name', {
        text: 'GARDEN EXPEDITION',
        x: 200,
        y: 90,
        width: 360,
        height: 52,
        fontFamily: 'display',
        fontSize: 34,
        fontWeight: 900,
        letterSpacing: 4,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.ecru,
      }),
      rule('Top rule', {
        x: 200,
        y: 140,
        width: 280,
        height: 3,
        fill: THREAD.ecru,
      }),
      slot('badge', 'Number', {
        text: '06',
        x: 200,
        y: 250,
        width: 300,
        height: 200,
        fontFamily: 'display',
        fontSize: 190,
        fontWeight: 900,
        lineHeight: 1,
        align: 'center',
        color: THREAD.ecru,
      }),
      rule('Bottom rule', {
        x: 200,
        y: 358,
        width: 280,
        height: 3,
        fill: THREAD.ecru,
      }),
      slot('subtitle', 'Name', {
        text: 'WREN',
        x: 200,
        y: 402,
        width: 340,
        height: 36,
        fontFamily: 'display',
        fontSize: 28,
        fontWeight: 800,
        letterSpacing: 8,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.lemon,
      }),
    ],
  },
];

/* -- Monogram: initials, small and precise. ------------------------------- */

const APPAREL_MONOGRAM = [
  {
    id: 'apparel-monogram-circle',
    name: 'Circle Monogram',
    category: 'Monogram',
    description:
      'A small ringed monogram sized for a left-chest pocket placement.',
    artboard: POCKET,
    substrate: {
      garment: 'tee',
      color: 'cream',
      accent: 'ink',
      placement: 'pocket',
      finish: 'satin',
    },
    layers: [
      oval('Ring', { x: 90, y: 74, width: 128, height: 128, fill: THREAD.ink }),
      oval('Ring field', {
        x: 90,
        y: 74,
        width: 112,
        height: 112,
        fill: THREAD.bone,
      }),
      slot('badge', 'Initials', {
        text: 'MW',
        x: 90,
        y: 68,
        width: 100,
        height: 42,
        fontFamily: 'serif',
        fontSize: 38,
        fontWeight: 700,
        letterSpacing: 2,
        align: 'center',
        color: THREAD.ink,
      }),
      slot('caption', 'Caption', {
        text: 'EST. 2020',
        x: 90,
        y: 104,
        width: 100,
        height: 12,
        fontFamily: 'sans',
        fontSize: 9,
        fontWeight: 600,
        letterSpacing: 4,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.graphite,
      }),
      slot('title', 'Name', {
        text: 'MAYA WREN',
        x: 90,
        y: 156,
        width: 164,
        height: 16,
        fontFamily: 'sans',
        fontSize: 11,
        fontWeight: 700,
        letterSpacing: 4,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.ink,
      }),
    ],
  },
  {
    id: 'apparel-monogram-stacked',
    name: 'Stacked Initials',
    category: 'Monogram',
    description:
      'Oversized serif initials over a short rule, with the full name spelled out under it.',
    artboard: CHEST,
    substrate: {
      garment: 'tee',
      color: 'pine',
      accent: 'ecru',
      placement: 'chest',
      finish: 'screen',
    },
    layers: [
      slot('badge', 'Initials', {
        text: 'M W',
        x: 180,
        y: 110,
        width: 300,
        height: 120,
        fontFamily: 'serif',
        fontSize: 108,
        fontWeight: 700,
        letterSpacing: 6,
        align: 'center',
        color: THREAD.ecru,
      }),
      rule('Rule', {
        x: 180,
        y: 182,
        width: 180,
        height: 2,
        fill: THREAD.gold,
      }),
      slot('title', 'Name', {
        text: 'MAYA WREN',
        x: 180,
        y: 214,
        width: 300,
        height: 30,
        fontFamily: 'serif',
        fontSize: 24,
        fontWeight: 500,
        letterSpacing: 3,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.ecru,
      }),
      slot('caption', 'Caption', {
        text: 'SIX YEARS BRAVE',
        x: 180,
        y: 254,
        width: 300,
        height: 16,
        fontFamily: 'sans',
        fontSize: 11,
        fontWeight: 500,
        letterSpacing: 5,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.dust,
      }),
    ],
  },
];

/* -- Mascot: a character crest, and a two-character back print. ----------- */

const APPAREL_MASCOT = [
  {
    id: 'apparel-mascot-crest',
    name: 'Mascot Crest',
    category: 'Mascot',
    description:
      'A single character above a display wordmark, topped by a small ruled eyebrow.',
    artboard: CHEST,
    substrate: {
      garment: 'hoodie',
      color: 'slate',
      accent: 'sky',
      placement: 'chest',
      finish: 'satin',
    },
    layers: [
      slot('eyebrow', 'Eyebrow', {
        text: 'FIELD CREW',
        x: 180,
        y: 34,
        width: 320,
        height: 18,
        fontFamily: 'sans',
        fontSize: 13,
        fontWeight: 600,
        letterSpacing: 5,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.sky,
      }),
      rule('Eyebrow rule', {
        x: 180,
        y: 56,
        width: 120,
        height: 2,
        fill: THREAD.sky,
      }),
      art('Mascot', {
        art: 'mascot_finley',
        x: 180,
        y: 132,
        width: 150,
        height: 150,
      }),
      slot('title', 'Title', {
        text: 'FINLEY & ME',
        x: 180,
        y: 222,
        width: 320,
        height: 40,
        fontFamily: 'display',
        fontSize: 34,
        fontWeight: 800,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.ecru,
      }),
      slot('subtitle', 'Subtitle', {
        text: 'ALWAYS OUT EXPLORING',
        x: 180,
        y: 258,
        width: 320,
        height: 20,
        fontFamily: 'sans',
        fontSize: 14,
        fontWeight: 500,
        letterSpacing: 4,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.sky,
      }),
    ],
  },
  {
    id: 'apparel-mascot-duo',
    name: 'Sidekick Duo',
    category: 'Mascot',
    description:
      'Two characters overlapping across a hero backprint, with a script sign-off.',
    artboard: BACK,
    substrate: {
      garment: 'hoodie',
      color: 'navy',
      accent: 'rose',
      placement: 'back',
      finish: 'puff',
    },
    layers: [
      slot('eyebrow', 'Eyebrow', {
        text: 'THE WHOLE CREW',
        x: 200,
        y: 72,
        width: 360,
        height: 18,
        fontFamily: 'sans',
        fontSize: 13,
        fontWeight: 600,
        letterSpacing: 6,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.rose,
      }),
      art('Mascot', {
        art: 'mascot_luna',
        x: 142,
        y: 190,
        width: 180,
        height: 180,
      }),
      mark('Sidekick', {
        art: 'mascot_sparky',
        x: 272,
        y: 248,
        width: 130,
        height: 130,
      }),
      slot('title', 'Title', {
        text: 'BEST OF FRIENDS',
        x: 200,
        y: 346,
        width: 360,
        height: 48,
        fontFamily: 'display',
        fontSize: 40,
        fontWeight: 900,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.ecru,
      }),
      slot('subtitle', 'Subtitle', {
        text: 'Maya, Luna and Sparky',
        x: 200,
        y: 396,
        width: 360,
        height: 26,
        fontFamily: 'cursive',
        fontSize: 20,
        fontWeight: 600,
        align: 'center',
        color: THREAD.rose,
      }),
      slot('caption', 'Caption', {
        text: 'SINCE THE SUMMER SHE TURNED SIX',
        x: 200,
        y: 438,
        width: 360,
        height: 16,
        fontFamily: 'sans',
        fontSize: 11,
        fontWeight: 500,
        letterSpacing: 4,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.dust,
      }),
    ],
  },
];

/* -- Streetwear: heavy stacks and a rotated side tag. --------------------- */

const APPAREL_STREET = [
  {
    id: 'apparel-street-stack',
    name: 'Street Stack',
    category: 'Streetwear',
    description:
      'Heavy stacked type across the back with a knocked-out band cutting through it.',
    artboard: BACK,
    substrate: {
      garment: 'tee',
      color: 'navy',
      accent: 'kelly',
      placement: 'back',
      finish: 'screen',
    },
    layers: [
      slot('eyebrow', 'Eyebrow', {
        text: 'GARDEN DIVISION',
        x: 200,
        y: 62,
        width: 380,
        height: 18,
        fontFamily: 'sans',
        fontSize: 13,
        fontWeight: 700,
        letterSpacing: 8,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.kelly,
      }),
      slot('title', 'Title', {
        text: 'BRAVE OUT HERE',
        x: 200,
        y: 172,
        width: 380,
        height: 190,
        fontFamily: 'display',
        fontSize: 76,
        fontWeight: 900,
        lineHeight: 0.92,
        letterSpacing: -2,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.ecru,
      }),
      panel('Band', {
        x: 200,
        y: 300,
        width: 380,
        height: 40,
        radius: 0,
        fill: THREAD.kelly,
      }),
      slot('subtitle', 'Subtitle', {
        text: 'MAYA WREN / NO. 06',
        x: 200,
        y: 300,
        width: 360,
        height: 24,
        fontFamily: 'display',
        fontSize: 19,
        fontWeight: 800,
        letterSpacing: 5,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.ink,
      }),
      slot('caption', 'Caption', {
        text: 'MADE ONCE, WORN EVERY DAY, WASHED COLD',
        x: 200,
        y: 362,
        width: 380,
        height: 40,
        fontFamily: 'sans',
        fontSize: 12,
        fontWeight: 500,
        lineHeight: 1.5,
        letterSpacing: 2,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.dust,
      }),
      mark('Sneaker', {
        art: 'sneaker',
        x: 200,
        y: 428,
        width: 110,
        height: 80,
      }),
    ],
  },
  {
    id: 'apparel-street-side-tag',
    name: 'Side Tag',
    category: 'Streetwear',
    description:
      'A rotated wordmark running up the left edge beside a small left-aligned block.',
    artboard: CHEST,
    substrate: {
      garment: 'jacket',
      color: 'slate',
      accent: 'gold',
      placement: 'chest',
      finish: 'screen',
    },
    layers: [
      slot('title', 'Side wordmark', {
        text: 'EXPLORER',
        x: 54,
        y: 150,
        width: 240,
        height: 44,
        rotation: -90,
        fontFamily: 'display',
        fontSize: 34,
        fontWeight: 900,
        letterSpacing: 4,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.ecru,
      }),
      rule('Edge rule', {
        x: 96,
        y: 150,
        width: 2,
        height: 240,
        fill: THREAD.gold,
      }),
      slot('subtitle', 'Subtitle', {
        text: 'MAYA WREN',
        x: 210,
        y: 112,
        width: 250,
        height: 34,
        fontFamily: 'display',
        fontSize: 26,
        fontWeight: 800,
        textTransform: 'uppercase',
        align: 'left',
        color: THREAD.ecru,
      }),
      slot('caption', 'Caption', {
        text: 'Six years old, one set of muddy boots, no fear of the dark.',
        x: 210,
        y: 164,
        width: 250,
        height: 48,
        fontFamily: 'sans',
        fontSize: 12,
        fontWeight: 400,
        lineHeight: 1.5,
        align: 'left',
        color: THREAD.dust,
      }),
      slot('badge', 'Badge', {
        text: 'NO. 06',
        x: 210,
        y: 216,
        width: 250,
        height: 20,
        fontFamily: 'sans',
        fontSize: 12,
        fontWeight: 700,
        letterSpacing: 5,
        textTransform: 'uppercase',
        align: 'left',
        color: THREAD.lemon,
      }),
    ],
  },
];

/* -- Nameplate & Badge: the script signature and the sewn patch. ---------- */

const APPAREL_MARKS = [
  {
    id: 'apparel-nameplate-script',
    name: 'Script Nameplate',
    category: 'Nameplate',
    description:
      'A flowing script name over a short rule, with a small heart set above it.',
    artboard: CHEST,
    substrate: {
      garment: 'kicks',
      color: 'cream',
      accent: 'rose',
      placement: 'chest',
      finish: 'chain',
    },
    layers: [
      mark('Heart', {
        art: 'heart',
        x: 180,
        y: 62,
        width: 48,
        height: 48,
        tint: THREAD.rose,
      }),
      slot('title', 'Name', {
        text: 'Maya Wren',
        x: 180,
        y: 128,
        width: 330,
        height: 76,
        fontFamily: 'cursive',
        fontSize: 58,
        fontWeight: 600,
        align: 'center',
        color: THREAD.navy,
      }),
      rule('Rule', {
        x: 180,
        y: 176,
        width: 200,
        height: 2,
        fill: THREAD.rose,
      }),
      slot('subtitle', 'Subtitle', {
        text: 'SIX YEARS BRAVE',
        x: 180,
        y: 206,
        width: 300,
        height: 22,
        fontFamily: 'sans',
        fontSize: 15,
        fontWeight: 600,
        letterSpacing: 6,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.graphite,
      }),
      slot('caption', 'Caption', {
        text: 'STITCHED BY HAND, JUNE 2026',
        x: 180,
        y: 254,
        width: 300,
        height: 14,
        fontFamily: 'sans',
        fontSize: 10,
        fontWeight: 500,
        letterSpacing: 4,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.dust,
      }),
    ],
  },
  {
    id: 'apparel-badge-patch',
    name: 'Sewn Patch',
    category: 'Badge',
    description:
      'A round chain-stitched patch: ringed border, centred compass and a curved footer line.',
    artboard: PATCH,
    substrate: {
      garment: 'jacket',
      color: 'pine',
      accent: 'gold',
      placement: 'pocket',
      finish: 'chain',
    },
    layers: [
      oval('Patch ring', {
        x: 120,
        y: 120,
        width: 210,
        height: 210,
        fill: THREAD.gold,
      }),
      oval('Patch field', {
        x: 120,
        y: 120,
        width: 186,
        height: 186,
        fill: THREAD.pine,
      }),
      slot('eyebrow', 'Eyebrow', {
        text: 'FIELD CREW',
        x: 120,
        y: 66,
        width: 150,
        height: 14,
        fontFamily: 'sans',
        fontSize: 10,
        fontWeight: 700,
        letterSpacing: 4,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.lemon,
      }),
      art('Compass', {
        art: 'compass',
        x: 120,
        y: 112,
        width: 72,
        height: 72,
        tint: THREAD.lemon,
      }),
      slot('title', 'Title', {
        text: 'MAYA WREN',
        x: 120,
        y: 162,
        width: 160,
        height: 26,
        fontFamily: 'display',
        fontSize: 20,
        fontWeight: 800,
        letterSpacing: 2,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.bone,
      }),
      slot('caption', 'Caption', {
        text: 'AGE SIX',
        x: 120,
        y: 186,
        width: 160,
        height: 12,
        fontFamily: 'sans',
        fontSize: 9,
        fontWeight: 600,
        letterSpacing: 3,
        textTransform: 'uppercase',
        align: 'center',
        color: THREAD.ecru,
      }),
    ],
  },
];

/* =========================================================== book ======== */

/* -- Covers: front-cover compositions at 420 x 540. ----------------------- */

const BOOK_COVERS = [
  {
    id: 'book-classic-storybook',
    name: 'Classic Storybook',
    category: 'Covers',
    description:
      'Ruled top and bottom, a serif title with a script sub-line, and the hero underneath.',
    artboard: COVER,
    substrate: { theme: 'magic', edition: 'hardcover' },
    layers: [
      rule('Top rule', {
        x: 210,
        y: 46,
        width: 340,
        height: 2,
        fill: PAGE.gilt,
      }),
      slot('eyebrow', 'Series', {
        text: 'THE WHISPERING WOODS',
        x: 210,
        y: 80,
        width: 320,
        height: 18,
        fontFamily: 'sans',
        fontSize: 13,
        fontWeight: 600,
        letterSpacing: 5,
        textTransform: 'uppercase',
        align: 'center',
        color: PAGE.gilt,
      }),
      slot('title', 'Title', {
        text: 'The Bravest Explorer',
        x: 210,
        y: 172,
        width: 320,
        height: 116,
        fontFamily: 'serif',
        fontSize: 48,
        fontWeight: 700,
        lineHeight: 1.05,
        align: 'center',
        color: PAGE.cream,
      }),
      slot('subtitle', 'Subtitle', {
        text: 'and the Door in the Old Oak',
        x: 210,
        y: 252,
        width: 300,
        height: 26,
        fontFamily: 'cursive',
        fontSize: 19,
        fontWeight: 500,
        align: 'center',
        color: PAGE.lemon,
      }),
      art('Hero', {
        art: 'mascot_penny',
        x: 210,
        y: 356,
        width: 170,
        height: 170,
      }),
      rule('Bottom rule', {
        x: 210,
        y: 494,
        width: 340,
        height: 2,
        fill: PAGE.gilt,
      }),
      slot('caption', 'Dedication line', {
        text: 'A STORY FOR MAYA, AGE SIX',
        x: 210,
        y: 462,
        width: 320,
        height: 16,
        fontFamily: 'sans',
        fontSize: 12,
        fontWeight: 500,
        letterSpacing: 4,
        textTransform: 'uppercase',
        align: 'center',
        color: PAGE.starlight,
      }),
    ],
  },
  {
    id: 'book-adventure-title',
    name: 'Adventure Title',
    category: 'Covers',
    description:
      'A full-bleed night panel across the top, then a hard uppercase title under a gold rule.',
    artboard: COVER,
    substrate: { theme: 'space', edition: 'deluxe' },
    layers: [
      panel('Night panel', {
        x: 210,
        y: 150,
        width: 420,
        height: 300,
        radius: 0,
        fill: PAGE.night,
      }),
      mark('Star', { art: 'star', x: 68, y: 68, width: 36, height: 36 }),
      mark('Sparkle', {
        art: 'sparkle',
        x: 350,
        y: 234,
        width: 28,
        height: 28,
      }),
      art('Rocket', { art: 'rocket', x: 210, y: 150, width: 180, height: 180 }),
      slot('title', 'Title', {
        text: 'Beyond The Last Star',
        x: 210,
        y: 352,
        width: 360,
        height: 100,
        fontFamily: 'sans',
        fontSize: 44,
        fontWeight: 800,
        lineHeight: 1,
        letterSpacing: 1,
        textTransform: 'uppercase',
        align: 'center',
        color: PAGE.cream,
      }),
      rule('Title rule', {
        x: 210,
        y: 412,
        width: 120,
        height: 3,
        fill: PAGE.lemon,
      }),
      slot('subtitle', 'Subtitle', {
        text: 'BOOK ONE OF THE VOYAGES',
        x: 210,
        y: 444,
        width: 340,
        height: 22,
        fontFamily: 'sans',
        fontSize: 15,
        fontWeight: 600,
        letterSpacing: 3,
        textTransform: 'uppercase',
        align: 'center',
        color: PAGE.lemon,
      }),
      slot('caption', 'Byline', {
        text: 'WITH MAYA WREN, NAVIGATOR',
        x: 210,
        y: 498,
        width: 340,
        height: 16,
        fontFamily: 'sans',
        fontSize: 11,
        fontWeight: 500,
        letterSpacing: 4,
        textTransform: 'uppercase',
        align: 'center',
        color: PAGE.dusk,
      }),
    ],
  },
  {
    id: 'book-keepsake-plate',
    name: 'Keepsake Plate',
    category: 'Covers',
    description:
      'A gilt-edged oval plate holding a script title and a two-line dedication.',
    artboard: COVER,
    substrate: { theme: 'magic', edition: 'deluxe' },
    layers: [
      oval('Plate edge', {
        x: 210,
        y: 250,
        width: 304,
        height: 344,
        fill: PAGE.gilt,
      }),
      oval('Plate', {
        x: 210,
        y: 250,
        width: 292,
        height: 332,
        fill: PAGE.cream,
      }),
      slot('eyebrow', 'Eyebrow', {
        text: 'A KEEPSAKE EDITION',
        x: 210,
        y: 142,
        width: 220,
        height: 16,
        fontFamily: 'sans',
        fontSize: 11,
        fontWeight: 600,
        letterSpacing: 5,
        textTransform: 'uppercase',
        align: 'center',
        color: PAGE.antique,
      }),
      slot('title', 'Title', {
        text: 'The Bravest Explorer',
        x: 210,
        y: 224,
        width: 250,
        height: 100,
        fontFamily: 'cursive',
        fontSize: 42,
        fontWeight: 600,
        lineHeight: 1.1,
        align: 'center',
        color: PAGE.cocoa,
      }),
      rule('Plate rule', {
        x: 210,
        y: 292,
        width: 70,
        height: 2,
        fill: PAGE.gilt,
      }),
      slot('subtitle', 'Dedication', {
        text: 'For Maya, on her sixth birthday',
        x: 210,
        y: 324,
        width: 240,
        height: 40,
        fontFamily: 'serif',
        fontSize: 15,
        fontWeight: 400,
        lineHeight: 1.4,
        align: 'center',
        color: PAGE.bark,
      }),
      mark('Rose', {
        art: 'rose',
        x: 210,
        y: 382,
        width: 56,
        height: 56,
        tint: PAGE.gilt,
      }),
      slot('caption', 'Footer', {
        text: 'PRINTED ONCE, IN JUNE 2026',
        x: 210,
        y: 492,
        width: 320,
        height: 16,
        fontFamily: 'sans',
        fontSize: 11,
        fontWeight: 500,
        letterSpacing: 4,
        textTransform: 'uppercase',
        align: 'center',
        color: PAGE.dusk,
      }),
    ],
  },
  {
    id: 'book-modern-picture',
    name: 'Modern Picture Book',
    category: 'Covers',
    description:
      'A flat colour block, an off-centre character and a left-aligned title hung off the margin.',
    artboard: COVER,
    substrate: { theme: 'sneaker', edition: 'softcover' },
    layers: [
      panel('Colour block', {
        x: 210,
        y: 190,
        width: 420,
        height: 380,
        radius: 0,
        fill: PAGE.violet,
      }),
      slot('title', 'Title', {
        text: 'City Of Bright Sneakers',
        x: 176,
        y: 120,
        width: 260,
        height: 96,
        fontFamily: 'sans',
        fontSize: 38,
        fontWeight: 800,
        lineHeight: 1.02,
        align: 'left',
        color: PAGE.cream,
      }),
      slot('subtitle', 'Subtitle', {
        text: 'A story about fast feet',
        x: 131,
        y: 196,
        width: 170,
        height: 24,
        fontFamily: 'sans',
        fontSize: 15,
        fontWeight: 500,
        align: 'left',
        color: PAGE.lilac,
      }),
      art('Hero', {
        art: 'mascot_carty',
        x: 310,
        y: 280,
        width: 170,
        height: 170,
      }),
      rule('Margin rule', {
        x: 90,
        y: 412,
        width: 88,
        height: 3,
        fill: PAGE.lemon,
      }),
      slot('caption', 'Caption', {
        text: 'WRITTEN AND DRAWN FOR MAYA WREN, WHO NEVER WALKS ANYWHERE',
        x: 176,
        y: 448,
        width: 260,
        height: 34,
        fontFamily: 'sans',
        fontSize: 12,
        fontWeight: 500,
        lineHeight: 1.5,
        letterSpacing: 2,
        textTransform: 'uppercase',
        align: 'left',
        color: PAGE.slate,
      }),
      slot('badge', 'Edition', {
        text: 'BOOK ONE',
        x: 356,
        y: 458,
        width: 88,
        height: 24,
        fontFamily: 'sans',
        fontSize: 12,
        fontWeight: 700,
        letterSpacing: 3,
        textTransform: 'uppercase',
        align: 'right',
        color: PAGE.lavender,
      }),
    ],
  },
];

/* -- Spreads: two facing pages at 720 x 460. ------------------------------ */

const BOOK_SPREADS = [
  {
    id: 'book-spread-story-left',
    name: 'Story Left, Art Right',
    category: 'Spreads',
    description:
      'Prose on the left page, the scene on the right, divided by a gutter rule.',
    artboard: SPREAD,
    substrate: { theme: 'dino', edition: 'hardcover' },
    layers: [
      rule('Gutter', {
        x: 360,
        y: 230,
        width: 2,
        height: 380,
        fill: PAGE.dusk,
        opacity: 0.5,
      }),
      slot('eyebrow', 'Chapter', {
        text: 'CHAPTER THREE',
        x: 190,
        y: 76,
        width: 260,
        height: 16,
        fontFamily: 'sans',
        fontSize: 11,
        fontWeight: 600,
        letterSpacing: 5,
        textTransform: 'uppercase',
        align: 'left',
        color: PAGE.dusk,
      }),
      slot('title', 'Chapter title', {
        text: 'The Valley Of Tall Ferns',
        x: 190,
        y: 132,
        width: 260,
        height: 66,
        fontFamily: 'serif',
        fontSize: 30,
        fontWeight: 700,
        lineHeight: 1.08,
        align: 'left',
        color: PAGE.cream,
      }),
      slot('body', 'Prose', {
        text: 'Maya held very still. Somewhere past the ferns something enormous was chewing, slowly, the way you chew when nothing in the world has ever frightened you.',
        x: 190,
        y: 252,
        width: 260,
        height: 152,
        fontFamily: 'serif',
        fontSize: 15,
        fontWeight: 400,
        lineHeight: 1.7,
        align: 'left',
        color: PAGE.starlight,
      }),
      slot('caption', 'Folio', {
        text: 'PAGE ELEVEN',
        x: 190,
        y: 392,
        width: 260,
        height: 14,
        fontFamily: 'sans',
        fontSize: 10,
        fontWeight: 500,
        letterSpacing: 3,
        textTransform: 'uppercase',
        align: 'left',
        color: PAGE.dusk,
      }),
      art('Scene', {
        art: 'mascot_dexter',
        x: 540,
        y: 214,
        width: 230,
        height: 230,
      }),
      slot('subtitle', 'Art caption', {
        text: 'Dexter, who was not frightening at all',
        x: 540,
        y: 372,
        width: 260,
        height: 24,
        fontFamily: 'cursive',
        fontSize: 16,
        fontWeight: 500,
        align: 'center',
        color: PAGE.lemon,
      }),
    ],
  },
  {
    id: 'book-spread-full-scene',
    name: 'Full Bleed Scene',
    category: 'Spreads',
    description:
      'One scene running across both pages with the line of prose in a soft bar at the foot.',
    artboard: SPREAD,
    substrate: { theme: 'space', edition: 'deluxe' },
    layers: [
      panel('Sky', {
        x: 360,
        y: 230,
        width: 720,
        height: 460,
        radius: 0,
        fill: PAGE.night,
      }),
      mark('Planet', {
        art: 'planet',
        x: 576,
        y: 110,
        width: 140,
        height: 140,
      }),
      mark('Star', { art: 'star', x: 118, y: 84, width: 40, height: 40 }),
      mark('Sparkle', {
        art: 'sparkle',
        x: 250,
        y: 150,
        width: 26,
        height: 26,
      }),
      art('Ship', {
        art: 'spaceship',
        x: 300,
        y: 232,
        width: 190,
        height: 190,
      }),
      slot('title', 'Chapter title', {
        text: 'The Long Dark',
        x: 190,
        y: 80,
        width: 260,
        height: 30,
        fontFamily: 'serif',
        fontSize: 22,
        fontWeight: 700,
        align: 'left',
        color: PAGE.cream,
      }),
      panel('Caption bar', {
        x: 360,
        y: 396,
        width: 640,
        height: 76,
        radius: 12,
        fill: PAGE.slate,
        opacity: 0.85,
      }),
      slot('body', 'Prose', {
        text: 'They flew past the last lit window on the last known street, and then there was only the long dark and the two of them in it.',
        x: 360,
        y: 386,
        width: 600,
        height: 46,
        fontFamily: 'serif',
        fontSize: 17,
        fontWeight: 400,
        lineHeight: 1.5,
        align: 'center',
        color: PAGE.starlight,
      }),
      slot('caption', 'Folio', {
        text: 'PAGES EIGHTEEN AND NINETEEN',
        x: 360,
        y: 428,
        width: 600,
        height: 14,
        fontFamily: 'sans',
        fontSize: 10,
        fontWeight: 500,
        letterSpacing: 4,
        textTransform: 'uppercase',
        align: 'center',
        color: PAGE.dusk,
      }),
    ],
  },
  {
    id: 'book-spread-two-panels',
    name: 'Two Panels',
    category: 'Spreads',
    description:
      'Two rounded panels side by side, each captioned, under a shared spread title.',
    artboard: SPREAD,
    substrate: { theme: 'magic', edition: 'hardcover' },
    layers: [
      panel('Panel left', {
        x: 190,
        y: 196,
        width: 260,
        height: 260,
        radius: 16,
        fill: PAGE.slate,
      }),
      panel('Panel right', {
        x: 530,
        y: 196,
        width: 260,
        height: 260,
        radius: 16,
        fill: PAGE.slate,
      }),
      art('Panel art left', {
        art: 'mascot_finley',
        x: 190,
        y: 190,
        width: 160,
        height: 160,
      }),
      mark('Panel art right', {
        art: 'castle',
        x: 530,
        y: 190,
        width: 170,
        height: 170,
      }),
      slot('title', 'Spread title', {
        text: 'Two Ways Into The Woods',
        x: 360,
        y: 64,
        width: 600,
        height: 36,
        fontFamily: 'serif',
        fontSize: 28,
        fontWeight: 700,
        align: 'center',
        color: PAGE.cream,
      }),
      slot('subtitle', 'Left caption', {
        text: 'The short way',
        x: 190,
        y: 372,
        width: 260,
        height: 22,
        fontFamily: 'sans',
        fontSize: 14,
        fontWeight: 600,
        letterSpacing: 2,
        align: 'center',
        color: PAGE.lemon,
      }),
      slot('caption', 'Right caption', {
        text: 'The interesting way',
        x: 530,
        y: 372,
        width: 260,
        height: 22,
        fontFamily: 'sans',
        fontSize: 14,
        fontWeight: 600,
        letterSpacing: 2,
        align: 'center',
        color: PAGE.lemon,
      }),
      slot('body', 'Prose', {
        text: 'Maya looked at both of them for exactly as long as it takes to decide nothing at all, and then took the interesting one.',
        x: 360,
        y: 424,
        width: 600,
        height: 24,
        fontFamily: 'serif',
        fontSize: 13,
        fontWeight: 400,
        lineHeight: 1.5,
        align: 'center',
        color: PAGE.starlight,
      }),
    ],
  },
];

/* -- Front matter: the quiet dedication page. ----------------------------- */

const BOOK_FRONT_MATTER = [
  {
    id: 'book-dedication-plate',
    name: 'Dedication Page',
    category: 'Front Matter',
    description:
      'A single quiet page: a small mark, a short rule and a centred dedication in wide margins.',
    artboard: COVER,
    substrate: { theme: 'magic', edition: 'hardcover' },
    layers: [
      mark('Sparkle', {
        art: 'sparkle',
        x: 210,
        y: 150,
        width: 40,
        height: 40,
        tint: PAGE.gilt,
      }),
      rule('Short rule', {
        x: 210,
        y: 206,
        width: 60,
        height: 1,
        fill: PAGE.gilt,
      }),
      slot('title', 'Dedication heading', {
        text: 'FOR MAYA',
        x: 210,
        y: 252,
        width: 280,
        height: 32,
        fontFamily: 'serif',
        fontSize: 22,
        fontWeight: 600,
        letterSpacing: 4,
        textTransform: 'uppercase',
        align: 'center',
        color: PAGE.cream,
      }),
      slot('body', 'Dedication', {
        text: 'Who checked under the bed for the rest of us, and reported back that it was perfectly fine down there.',
        x: 210,
        y: 332,
        width: 280,
        height: 104,
        fontFamily: 'serif',
        fontSize: 16,
        fontWeight: 400,
        lineHeight: 1.8,
        align: 'center',
        color: PAGE.starlight,
      }),
      slot('caption', 'Footer', {
        text: 'JUNE 2026',
        x: 210,
        y: 438,
        width: 280,
        height: 16,
        fontFamily: 'sans',
        fontSize: 11,
        fontWeight: 500,
        letterSpacing: 3,
        textTransform: 'uppercase',
        align: 'center',
        color: PAGE.dusk,
      }),
    ],
  },
];

/* ========================================================== exports ====== */

export const TEMPLATES_BY_MODE = {
  poster: [
    ...POSTER_EDITORIAL,
    ...POSTER_BOLD,
    ...POSTER_ILLUSTRATED,
    ...POSTER_MINIMAL,
    ...POSTER_OCCASION,
  ],
  apparel: [
    ...APPAREL_VARSITY,
    ...APPAREL_MONOGRAM,
    ...APPAREL_MASCOT,
    ...APPAREL_STREET,
    ...APPAREL_MARKS,
  ],
  book: [...BOOK_COVERS, ...BOOK_SPREADS, ...BOOK_FRONT_MATTER],
};

export const TEMPLATE_MODES = Object.keys(TEMPLATES_BY_MODE);

/** Templates for a mode, already grouped for the picker's category headings. */
export const templateGroups = (mode) => {
  const groups = [];

  (TEMPLATES_BY_MODE[mode] ?? []).forEach((template) => {
    const existing = groups.find((g) => g.category === template.category);
    if (existing) existing.templates.push(template);
    else groups.push({ category: template.category, templates: [template] });
  });

  return groups;
};

export const findTemplate = (mode, id) =>
  (TEMPLATES_BY_MODE[mode] ?? []).find((template) => template.id === id) ??
  null;

/** The template a fresh editor opens on. */
export const defaultTemplate = (mode) =>
  (TEMPLATES_BY_MODE[mode] ?? [])[0] ?? null;
